org.gradle.jvmargs=-Xmx1G
org.gradle.caching=false
org.gradle.configuration-cache=false

# Plugin Metadata
plugin_group=hexvane
plugin_description=A grappling hook mod for Hytale with Star Slinger, Astral Tethers, and Galaxy in a Bottle!
plugin_author=Hexvane
plugin_website=
plugin_main_entrypoint=com.hexvane.starslinger.StarSlingerPlugin
server_version=>=0.6.0-pre.0 <0.7.0

# Star Slinger Debug Logging
# Set to true to enable verbose debug logging (useful for development)
# Set to false to disable excessive logging in production builds
starslinger_debug_logging=false
