org.gradle.jvmargs=-Xmx1G
org.gradle.caching=false
org.gradle.configuration-cache=false

# Plugin Metadata
plugin_group=hexvane
plugin_description=A grappling hook mod for Hytale with Star Grappler, Star Nodes, and Galaxy in a Bottle!
plugin_author=Hexvane
plugin_website=
plugin_main_entrypoint=com.hexvane.stargrappler.StarGrapplerPlugin
server_version=*
